// ⚠️ This file is auto-generated by integrations/routeGenerator.ts — do not edit manually. ⚠️

export type Route = {
  readonly key: string;
  readonly path: string;
  readonly title: string;
  readonly parent: Route | null;
  readonly sitemap: boolean;
  readonly isStagingOnly: boolean;
  readonly navOrder: number | null;
  readonly navLabel: string | null;
};

export const barrierefreiheit = {
  key: "barrierefreiheit",
  path: "/barrierefreiheit",
  title: "Barrierefreiheit",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const beispiele = {
  key: "beispiele",
  path: "/beispiele",
  title: "Beispiele für Digitaltauglichkeit",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const beispiele_prinzipien = {
  key: "beispiele_prinzipien",
  path: "/beispiele/prinzipien",
  title: "Die Prinzipien im Regelungstext",
  parent: beispiele,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const beispiele_visualisierungen = {
  key: "beispiele_visualisierungen",
  path: "/beispiele/visualisierungen",
  title: "Beispiele für Visualisierungen",
  parent: beispiele,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const dasIstNeu = {
  key: "dasIstNeu",
  path: "/das-ist-neu",
  title: "Das ist neu",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const datenschutz = {
  key: "datenschutz",
  path: "/datenschutz",
  title: "Datenschutzerklärung",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const dokumentation = {
  key: "dokumentation",
  path: "/dokumentation",
  title: "Dokumentation",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const dokumentation_absenden = {
  key: "dokumentation_absenden",
  path: "/dokumentation/absenden",
  title: "Absenden",
  parent: dokumentation,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const dokumentation_beteiligungsformate = {
  key: "dokumentation_beteiligungsformate",
  path: "/dokumentation/beteiligungsformate",
  title: "Beteiligungsformate",
  parent: dokumentation,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const dokumentation_hinweise = {
  key: "dokumentation_hinweise",
  path: "/dokumentation/hinweise",
  title: "Hinweise",
  parent: dokumentation,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const dokumentation_regelungsvorhabenTitel = {
  key: "dokumentation_regelungsvorhabenTitel",
  path: "/dokumentation/regelungsvorhaben-titel",
  title: "Regelungsvorhaben Titel",
  parent: dokumentation,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const dokumentation_zusammenfassung = {
  key: "dokumentation_zusammenfassung",
  path: "/dokumentation/zusammenfassung",
  title: "Zusammenfassung",
  parent: dokumentation,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const gesetzgebungsprozess = {
  key: "gesetzgebungsprozess",
  path: "/gesetzgebungsprozess",
  title: "Der Digitalcheck im Gesetzgebungsprozess",
  parent: null,
  sitemap: true,
  isStagingOnly: true,
  navOrder: null,
  navLabel: null,
} as const;

export const grundlagen = {
  key: "grundlagen",
  path: "/grundlagen",
  title: "Grundlagen",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const grundlagen_digitaltauglichkeit = {
  key: "grundlagen_digitaltauglichkeit",
  path: "/grundlagen/digitaltauglichkeit",
  title: "Digitaltauglichkeit",
  parent: grundlagen,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const grundlagen_normenkontrollrat = {
  key: "grundlagen_normenkontrollrat",
  path: "/grundlagen/normenkontrollrat",
  title: "Die Rolle des Nationalen Normenkontrollrats",
  parent: grundlagen,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const home = {
  key: "home",
  path: "/",
  title: "Startseite",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const impressum = {
  key: "impressum",
  path: "/impressum",
  title: "Impressum",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const interoperabel = {
  key: "interoperabel",
  path: "/interoperabel",
  title: "Interoperable Regelungen",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const interoperabel_faq = {
  key: "interoperabel_faq",
  path: "/interoperabel/faq",
  title: "Fragen und Antworten",
  parent: interoperabel,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const interoperabel_loesungen = {
  key: "interoperabel_loesungen",
  path: "/interoperabel/loesungen",
  title: "Interoperable Lösungen",
  parent: interoperabel,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const interoperabel_loesungen_coreVocabularies = {
  key: "interoperabel_loesungen_coreVocabularies",
  path: "/interoperabel/loesungen/core-vocabularies",
  title: "Semantic Core Vocabularies",
  parent: interoperabel_loesungen,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const interoperabel_loesungen_dcatAp = {
  key: "interoperabel_loesungen_dcatAp",
  path: "/interoperabel/loesungen/dcat-ap",
  title: "Data Catalogue Vocabulary Application Profile (DCAT-AP)",
  parent: interoperabel_loesungen,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const interoperabel_nationaleKontaktstelle = {
  key: "interoperabel_nationaleKontaktstelle",
  path: "/interoperabel/nationale-kontaktstelle",
  title: "Nationale Kontaktstelle",
  parent: interoperabel,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const methoden = {
  key: "methoden",
  path: "/methoden",
  title: "Regelung erarbeiten",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const methoden_fuenfPrinzipien = {
  key: "methoden_fuenfPrinzipien",
  path: "/methoden/fuenf-prinzipien",
  title: "Fünf Prinzipien",
  parent: methoden,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const methoden_interviewLeitfaden = {
  key: "methoden_interviewLeitfaden",
  path: "/methoden/interview-leitfaden",
  title: "Interview Leitfaden",
  parent: methoden,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const methoden_interviewLeitfadenSchritte = {
  key: "methoden_interviewLeitfadenSchritte",
  path: "/methoden/interview-leitfaden-schritte",
  title: "Interview Leitfaden Schritte",
  parent: methoden,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const methoden_itSystemeErfassen = {
  key: "methoden_itSystemeErfassen",
  path: "/methoden/it-systeme-erfassen",
  title: "IT-Systeme erfassen",
  parent: methoden,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const methoden_technischeUmsetzbarkeit = {
  key: "methoden_technischeUmsetzbarkeit",
  path: "/methoden/technische-umsetzbarkeit",
  title: "Technische Umsetzbarkeit sicherstellen",
  parent: methoden,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const methoden_visualisieren = {
  key: "methoden_visualisieren",
  path: "/methoden/visualisieren",
  title: "Visualisieren",
  parent: methoden,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const methoden_visualisieren_flussdiagramm = {
  key: "methoden_visualisieren_flussdiagramm",
  path: "/methoden/visualisieren/flussdiagramm",
  title: "Anleitung Flussdiagramme",
  parent: methoden_visualisieren,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const methoden_zustaendigeAkteurinnenAuflisten = {
  key: "methoden_zustaendigeAkteurinnenAuflisten",
  path: "/methoden/zustaendige-akteurinnen-auflisten",
  title: "Akteure auflisten",
  parent: methoden,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const sitemap = {
  key: "sitemap",
  path: "/sitemap",
  title: "Sitemap",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const unterstuetzung = {
  key: "unterstuetzung",
  path: "/unterstuetzung",
  title: "Unterstützungsangebote",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const vorpruefung = {
  key: "vorpruefung",
  path: "/vorpruefung",
  title: "Vorprüfung: Digitalbezug einschätzen",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const vorpruefung_automatisierung = {
  key: "vorpruefung_automatisierung",
  path: "/vorpruefung/automatisierung",
  title: "Automatisierung — Vorprüfung",
  parent: vorpruefung,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const vorpruefung_datenaustausch = {
  key: "vorpruefung_datenaustausch",
  path: "/vorpruefung/datenaustausch",
  title: "Datenaustausch — Vorprüfung",
  parent: vorpruefung,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const vorpruefung_ergebnis = {
  key: "vorpruefung_ergebnis",
  path: "/vorpruefung/ergebnis",
  title: "Ergebnis der Vorprüfung",
  parent: vorpruefung,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const vorpruefung_euBezug = {
  key: "vorpruefung_euBezug",
  path: "/vorpruefung/eu-bezug",
  title: "EU-Bezug — Vorprüfung",
  parent: vorpruefung,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const vorpruefung_hinweise = {
  key: "vorpruefung_hinweise",
  path: "/vorpruefung/hinweise",
  title: "Allgemeine Hinweise zur Vorprüfung",
  parent: vorpruefung,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const vorpruefung_itSystem = {
  key: "vorpruefung_itSystem",
  path: "/vorpruefung/it-system",
  title: "IT-System — Vorprüfung",
  parent: vorpruefung,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const vorpruefung_kommunikation = {
  key: "vorpruefung_kommunikation",
  path: "/vorpruefung/kommunikation",
  title: "Digitale Kommunikation — Vorprüfung",
  parent: vorpruefung,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const vorpruefung_verpflichtungenFuerBeteiligte = {
  key: "vorpruefung_verpflichtungenFuerBeteiligte",
  path: "/vorpruefung/verpflichtungen-fuer-beteiligte",
  title: "Verpflichtungen für Beteiligte — Vorprüfung",
  parent: vorpruefung,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const zahlenUndFakten = {
  key: "zahlenUndFakten",
  path: "/zahlen-und-fakten",
  title: "Zahlen und Fakten",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const allRoutes = [
  barrierefreiheit,
  beispiele,
  beispiele_prinzipien,
  beispiele_visualisierungen,
  dasIstNeu,
  datenschutz,
  dokumentation,
  dokumentation_absenden,
  dokumentation_beteiligungsformate,
  dokumentation_hinweise,
  dokumentation_regelungsvorhabenTitel,
  dokumentation_zusammenfassung,
  gesetzgebungsprozess,
  grundlagen,
  grundlagen_digitaltauglichkeit,
  grundlagen_normenkontrollrat,
  home,
  impressum,
  interoperabel,
  interoperabel_faq,
  interoperabel_loesungen,
  interoperabel_loesungen_coreVocabularies,
  interoperabel_loesungen_dcatAp,
  interoperabel_nationaleKontaktstelle,
  methoden,
  methoden_fuenfPrinzipien,
  methoden_interviewLeitfaden,
  methoden_interviewLeitfadenSchritte,
  methoden_itSystemeErfassen,
  methoden_technischeUmsetzbarkeit,
  methoden_visualisieren,
  methoden_visualisieren_flussdiagramm,
  methoden_zustaendigeAkteurinnenAuflisten,
  sitemap,
  unterstuetzung,
  vorpruefung,
  vorpruefung_automatisierung,
  vorpruefung_datenaustausch,
  vorpruefung_ergebnis,
  vorpruefung_euBezug,
  vorpruefung_hinweise,
  vorpruefung_itSystem,
  vorpruefung_kommunikation,
  vorpruefung_verpflichtungenFuerBeteiligte,
  zahlenUndFakten,
] as const;
