name: Build Docker

on:
  workflow_call:
    inputs:
      dockerImage:
        required: true
        type: string
      dockerImageArtifact:
        required: false
        type: string
        default: docker-image
        description: "The name of the Docker image artifact to upload."
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      SLACK_CHANNEL_ID:
        required: true

env:
  PACKAGE_NAME: digitalcheck-dito

permissions:
  contents: read

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Build app Docker container
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          load: true
          tags: ${{ inputs.dockerImage }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Docker image as artifact
        env:
          DOCKER_IMAGE: ${{ inputs.dockerImage }}
        run: docker save "$DOCKER_IMAGE" | gzip > /tmp/docker-image.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ inputs.dockerImageArtifact }}
          path: /tmp/docker-image.tar.gz
          retention-days: 1

      - name: Send failure to Slack
        uses: digitalservicebund/notify-on-failure-gha@5973d82d62439ebd6f0cf73d6836e6a81782e419 # v1.6.1
        if: failure()
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
