name: Check and Test

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

env:
  PACKAGE_NAME: digitalcheck-dito

permissions:
  contents: read

jobs:
  licenses-format-lint-typecheck-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Cache npm dependencies
        id: cache-npm-deps
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-npm-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Audit used licences
        run: npm run audit:licences

      - name: Fix formatting issues
        run: npm run format:fix

      - name: Lint
        run: npm run lint:fix

      - name: Check types
        run: npm run typecheck

      - name: Run unit tests
        run: npm test

      - name: Send failure to Slack
        uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf # v1.5.0
        if: ${{ failure() }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
