name: Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1" # every Monday at 10 am

jobs:
  link-checker:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Link Checker
        uses: digitalservicebund/link-checker-gha@b4d3978126a9ee74ab30845791150bf87690edf3 # v1.1.0
        with:
          SITEMAP_URL: "https://digitalcheck.bund.de/sitemap.xml"
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
