name: Nightly Tests

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2am
  # Allow to run this workflow manually
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-and-test:
    uses: ./.github/workflows/check-and-test.yml
    with:
      nightlyTests: true
    secrets: inherit
  create-unified-test-report:
    needs: [check-and-test]
    # Merge reports only if some shards have failed
    if: failure() && needs.check-and-test.result == 'failure'
    uses: ./.github/workflows/create-unified-test-report.yml
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
