name: Nightly Tests

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2am
  # Allow to run this workflow manually
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-and-test:
    uses: ./.github/workflows/check-and-test.yml
    secrets: inherit

  run-e2e-a11y-tests:
    uses: ./.github/workflows/run-e2e-a11y-tests.yml
    with:
      nightlyTests: true
    secrets: inherit

  create-unified-test-report:
    needs: [run-e2e-a11y-tests]
    # Merge reports only if E2E/A11y test shards have failed
    if: failure() && needs.run-e2e-a11y-tests.result == 'failure'
    uses: ./.github/workflows/create-unified-test-report.yml
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
