name: Pipeline

on:
  push:
    branches:
      - main
      - "staging/**"
  schedule:
    - cron: "0 0 * * 1" # Every Monday at Midnight UTC (docker images need not be older than 1 week)
  pull_request:
    branches: [main]
  # Allow to run this workflow manually
  workflow_dispatch:

permissions:
  contents: read

env:
  PACKAGE_NAME: digitalcheck-dito
  IMAGE_REF: ghcr.io/digitalservicebund/digitalcheck-dito
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

jobs:
  vulnerability-scan:
    permissions:
      contents: read
      packages: read
      security-events: write
    uses: ./.github/workflows/scan.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Ensure Talisman can operate on a valid revision range
      - name: Detect secrets with Talisman in incoming commits
        uses: digitalservicebund/talisman-secrets-scan-action@dd7513defb21028835988b40e89f7d10b3f66ed5

  check-and-test:
    uses: ./.github/workflows/check-and-test.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

  build-docker:
    uses: ./.github/workflows/build-docker.yml
    with:
      # env context is unavailable in with: when calling a reusable workflow
      dockerImage: ghcr.io/digitalservicebund/digitalcheck-dito:${{ github.sha }}
      dockerImageArtifact: docker-image
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

  run-e2e-a11y-tests:
    needs: [build-docker]
    uses: ./.github/workflows/run-e2e-a11y-tests.yml
    with:
      # env context is unavailable in with: when calling a reusable workflow
      dockerImage: ghcr.io/digitalservicebund/digitalcheck-dito:${{ github.sha }}
      dockerImageArtifact: docker-image
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

  create-unified-test-report:
    needs: [run-e2e-a11y-tests]
    # Merge reports only if E2E/A11y test shards have failed
    if: failure() && needs.run-e2e-a11y-tests.result == 'failure'
    uses: ./.github/workflows/create-unified-test-report.yml
    permissions:
      contents: read
      pages: write
      id-token: write

  push-image:
    needs: [vulnerability-scan, secret-scan, check-and-test, run-e2e-a11y-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # This is used to complete the identity challenge with sigstore/fulcio.
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Docker image
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: docker-image
          path: /tmp

      - name: Load and push Docker image
        if: ${{ github.event_name != 'pull_request' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/staging/'))}}
        run: |
          docker load < /tmp/docker-image.tar.gz
          docker tag ${{ env.IMAGE_REF }}:${{ github.sha }} ${{ env.IMAGE_REF }}
          docker push ${{ env.IMAGE_REF }}
          docker push ${{ env.IMAGE_REF }}:${{ github.sha }}

      - name: Load Docker image (pull request)
        if: ${{ github.event_name == 'pull_request' }}
        run: docker load < /tmp/docker-image.tar.gz

      - name: Generate cosign vulnerability scan record
        # Third-party action, pin to commit SHA
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          image-ref: ${{ env.IMAGE_REF }}:${{ github.sha }}
          format: "cosign-vuln"
          output: "${{ env.PACKAGE_NAME }}-vulnerabilities.json"

      - name: Upload cosign vulnerability scan record
        if: ${{ github.event_name != 'pull_request' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/staging/'))  }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: "${{ env.PACKAGE_NAME }}-vulnerabilities.json"
          path: "${{ env.PACKAGE_NAME }}-vulnerabilities.json"
          if-no-files-found: error

      - name: Install cosign
        if: ${{ github.event_name != 'pull_request' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/staging/'))  }}
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: "v2.6.0"

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/staging/')) }}
        run: cosign sign --yes ${{ env.IMAGE_REF }}:${{ github.sha }}

      - name: Attest the vulnerability scan
        if: ${{ github.event_name != 'pull_request' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/staging/')) }}
        run: cosign attest --yes --replace --predicate ${{ env.PACKAGE_NAME }}-vulnerabilities.json --type vuln ${{ env.IMAGE_REF }}:${{ github.sha }}

      - name: Send failure to Slack
        uses: digitalservicebund/notify-on-failure-gha@8570032b46ae9c2b976ec41567f595746fa44b4e # v1.6.1
        if: failure()
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

  deploy-to-staging-stackit:
    needs: [push-image]
    if: github.ref == 'refs/heads/main'
    permissions:
      packages: read
    uses: ./.github/workflows/deploy.yml
    concurrency: deploy
    with:
      environment_name: staging
      environment_url: https://digitalcheck.dev.tech.digitalservice.dev
    secrets:
      GITOPS_DIGITALCHECK_APP_ID: ${{ secrets.GITOPS_DIGITALCHECK_APP_ID }}
      GITOPS_DIGITALCHECK_APP_PRIVATE_KEY: ${{ secrets.GITOPS_DIGITALCHECK_APP_PRIVATE_KEY }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
      ARGOCD_SERVER_STACKIT: ${{ secrets.ARGOCD_SERVER_STACKIT }}
      METRICS_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
      METRICS_WEBHOOK_TOKEN: ${{ secrets.METRICS_WEBHOOK_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}

  deploy-to-production-stackit:
    needs: [push-image]
    if: github.ref == 'refs/heads/main'
    permissions:
      packages: read
    uses: ./.github/workflows/deploy.yml
    concurrency: deploy
    with:
      environment_name: production
      environment_url: https://digitalcheck.bund.de
    secrets:
      GITOPS_DIGITALCHECK_APP_ID: ${{ secrets.GITOPS_DIGITALCHECK_APP_ID }}
      GITOPS_DIGITALCHECK_APP_PRIVATE_KEY: ${{ secrets.GITOPS_DIGITALCHECK_APP_PRIVATE_KEY }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
      ARGOCD_SERVER_STACKIT: ${{ secrets.ARGOCD_SERVER_STACKIT }}
      METRICS_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
      METRICS_WEBHOOK_TOKEN: ${{ secrets.METRICS_WEBHOOK_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
