name: Run E2E and A11y Tests

on:
  workflow_call:
    inputs:
      dockerImage:
        required: true
        type: string
      dockerImageArtifact:
        required: false
        type: string
        default: docker-image
        description: "The name of the Docker image artifact to download."
      nightlyTests:
        required: false
        type: boolean
        description:
          "If enabled, extensive tests are executed sequentially with more
          devices and browsers."
        default: false
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      SLACK_CHANNEL_ID:
        required: true

env:
  PACKAGE_NAME: digitalcheck-dito

permissions:
  contents: read

jobs:
  run-e2e-a11y-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Cache Playwright dependencies
        id: cache-playwright-deps
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-playwright-

      - name: Install E2E & A11y test dependencies
        if:
          inputs.nightlyTests || steps.cache-playwright-deps.outputs.cache-hit ==
          'false'
        run: pnpm exec playwright install --with-deps

      - name: Download Docker image
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ inputs.dockerImageArtifact }}
          path: /tmp

      - name: Load Docker image
        run: docker load < /tmp/docker-image.tar.gz

      - name: Run nightly E2E tests
        if: inputs.nightlyTests
        id: e2e-nightly
        run: pnpm exec playwright test tests/e2e/
          --config=tests/playwright-nightly.config.ts --shard=${{
          matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          PLAYWRIGHT_USE_DOCKER: "true"
          PLAYWRIGHT_DOCKER_IMAGE: ${{ inputs.dockerImage }}

      - name: Run E2E tests
        if: ${{ !inputs.nightlyTests }}
        id: e2e
        run:
          pnpm exec playwright test tests/e2e/ --config=tests/playwright.config.ts
          --project="Desktop Chrome" --shard=${{ matrix.shardIndex }}/${{
          matrix.shardTotal }}
        env:
          NODE_OPTIONS: --trace-warnings
          PLAYWRIGHT_USE_DOCKER: "true"
          PLAYWRIGHT_DOCKER_IMAGE: ${{ inputs.dockerImage }}
          PUBLIC_STAGE: staging

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if:
          failure() && (steps.e2e.outcome == 'failure' || steps.e2e-nightly.outcome ==
          'failure')
        with:
          name: playwright-e2e-blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

      - name: Run nightly A11Y tests
        if: inputs.nightlyTests
        id: a11y-nightly
        run: pnpm exec playwright test tests/a11y/
          --config=tests/playwright-nightly.config.ts --shard=${{
          matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          PLAYWRIGHT_USE_DOCKER: "true"
          PLAYWRIGHT_DOCKER_IMAGE: ${{ inputs.dockerImage }}

      - name: Run A11y tests
        if: ${{ !inputs.nightlyTests }}
        id: a11y
        run:
          pnpm exec playwright test tests/a11y/ --config=tests/playwright.config.ts
          --project="Desktop Chrome" --shard=${{ matrix.shardIndex }}/${{
          matrix.shardTotal }}
        env:
          PLAYWRIGHT_USE_DOCKER: "true"
          PLAYWRIGHT_DOCKER_IMAGE: ${{ inputs.dockerImage }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if:
          failure() && (steps.a11y.outcome == 'failure' || steps.a11y-nightly.outcome
          == 'failure')
        with:
          name: playwright-a11y-blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  notify-e2e-a11y-failure:
    needs: [run-e2e-a11y-tests]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Send failure to Slack
        uses: digitalservicebund/notify-on-failure-gha@5973d82d62439ebd6f0cf73d6836e6a81782e419 # v1.6.1
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
